### ISSUE TITLE
Can't install because of dependency conflict

### ISSUE THREAD

**Issue by yasin-gorgij** [team-alembic/ash_authentication_phoenix#545]
Today I updated Phoenix and tried to use the getting started guide and it failed to install it using Igniter because the project depends on `phoenix_live_view ~> 0.18` and the latest Phoenix LiveView version is `1.0.0`.
 
Igniter version: `0.4.11`
Phoenix version: `1.7.17`

This is the error:
** (RuntimeError) Resolving Hex dependencies...
Resolution completed in 0.382s
Because "your app" depends on "ash_authentication_phoenix ~> 2.0" which depends on "phoenix_live_view ~> 0.18", "phoenix_live_view ~> 0.18" is required.
So, because "your app" depends on "phoenix_live_view ~> 1.0.0", version solving failed.
** (Mix) Hex dependency resolution failed

    (igniter 0.4.8) lib/igniter/util/install.ex:187: Igniter.Util.Install.get_deps!/2
    (igniter 0.4.8) lib/igniter/util/info.ex:46: Igniter.Util.Info.compose_install_and_validate!/6
    (igniter 0.4.8) lib/igniter/util/install.ex:77: Igniter.Util.Install.install/4
    (mix 1.17.3) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.3) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /usr/bin/mix:2: (file)

**Comment by zachdaniel** [comment]
I've published version `2.4.0` of `ash_authentication_phoenix` which depends on 1.0. Give that a shot :)

**Comment by yasin-gorgij** [comment]
Thank you.
It works now.
